POST http://localhost:80/cinema-service/auditoriums/create HTTP/1.1
Content-Type: application/json

{
  
    
    "AuditoriumName": "Grand Theater Hall",
    "Capacity": 250,
    "CreatedAt": "2025-03-15T19:31:21.718333033Z",
    "LastModifiedAt": "2025-03-15T19:31:21.718333033Z",
    "LastModifiedBy": "admin",
    "CreatedBy": "system",
    "IsDeleted": false
}


###
PUT http://localhost:80/cinema-service/auditoriums/update HTTP/1.1
Content-Type: application/json

{
   "ID": 351,
    "AuditoriumName": "conga",
    "Capacity": 250,
    "CreatedAt": "2025-03-15T19:31:21.718333033Z",
    "LastModifiedAt": "2025-03-15T19:31:21.718333033Z",
    "LastModifiedBy": "fd",
    "CreatedBy": "system",
    "IsDeleted": false
}

###
GET http://localhost:80/cinema-service/auditoriums/search?isDelete=false  HTTP/1.1



